application: guessworldcup2014
version: 25
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /
  script: main.app

- url: /index\.html.*
  script: main.app

- url: /list.*
  script: main.app

- url: /bet.*
  script: main.app

- url: /mybet.*
  script: main.app

- url: /list_by_date.*
  script: main.app

- url: /report.*
  script: main.app

- url: /pop.*
  script: main.app

- url: /bestbet.*
  script: main.app

- url: /eula.*
  script: main.app

- url: /admin.*
  script: admin.app

- url: /css
  static_dir: css
  mime_type: text/css

- url: /img
  static_dir: img
  mime_type: image

- url: /fonts
  static_dir: fonts
  mime_type: font/opentype

- url: /js/(.*)/(.*)
  static_files: js/\1/\2
  upload: js/(.*)/(.*)
  mime_type: application/javascript

- url: /js/(.*)
  static_files: js/\1
  upload: js/(.*)
  mime_type: application/javascript

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
