application: guess2014
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.app

- url: /list.*
  script: match_list.app
  login: required

- url: /bet.*
  script: user_bet.app
  login: required

- url: /admin.*
  script: admin.app
  login: admin

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /js
  static_dir: js

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
